# Generated by Django 5.1.1 on 2024-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_remove_schedulexam_userd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulexam',
            name='add',
            field=models.IntegerField(),
        ),
    ]
