# Generated by Django 5.1.1 on 2024-10-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_alter_schedulexam_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulexam',
            old_name='add',
            new_name='add_id',
        ),
    ]
