# Generated by Django 5.1.1 on 2024-10-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_rename_add_schedulexam_add_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='category',
        ),
    ]
