# Generated by Django 5.1.1 on 2024-10-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0005_remove_registrations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_section.category'),
            preserve_default=False,
        ),
    ]
