# Generated by Django 5.1.1 on 2024-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0007_alter_attempt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.AddField(
            model_name='attempt',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
