# Generated by Django 5.1.1 on 2024-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0008_remove_attempt_user_attempt_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='add_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
