# Generated by Django 5.1.1 on 2024-10-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0009_attempt_add_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='category',
        ),
    ]
