# Generated by Django 5.1.1 on 2024-10-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0010_remove_registrations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registuser',
            name='added_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registuser',
            name='added_on',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
