# Generated by Django 5.1.1 on 2024-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0011_registuser_added_by_registuser_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='registadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
