# Generated by Django 5.1.1 on 2024-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0012_registadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registadmin',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
