# Generated by Django 5.1.1 on 2024-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0013_registadmin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category_name',
        ),
        migrations.AddField(
            model_name='questions',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
