# Generated by Django 5.1.1 on 2024-10-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0014_remove_questions_category_name_questions_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_section.category'),
            preserve_default=False,
        ),
    ]
