# Generated by Django 5.1.1 on 2024-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0015_remove_questions_category_id_questions_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdownvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
