# Generated by Django 5.1.1 on 2024-10-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0016_dropdownvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulexam',
            name='add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.add_exam'),
        ),
    ]
