# Generated by Django 5.1.1 on 2024-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0017_alter_schedulexam_add_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulexam',
            name='add_id',
            field=models.IntegerField(),
        ),
    ]
