# Generated by Django 5.1.1 on 2024-11-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0018_alter_schedulexam_add_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_exam',
            name='date_of_test',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_exam',
            name='no_of_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_exam',
            name='time_of_test',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
