# Generated by Django 5.1.1 on 2024-11-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0019_add_exam_date_of_test_add_exam_no_of_questions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dropdownvalue',
        ),
    ]
