# Generated by Django 5.1.1 on 2024-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0020_delete_dropdownvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(max_length=200)),
            ],
        ),
    ]
