# Generated by Django 5.1.1 on 2024-11-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0021_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
    ]
