# Generated by Django 5.1.1 on 2024-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0022_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allowed_permit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
