# Generated by Django 5.1.1 on 2024-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0024_alter_role_allowed_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='super_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('roles', models.IntegerField()),
            ],
        ),
    ]
