# Generated by Django 5.1.1 on 2024-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0025_super_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='registadmin',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
