# Generated by Django 5.1.1 on 2024-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0026_registadmin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='allowed_permit',
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_permit',
            field=models.ManyToManyField(blank=True, to='admin_section.permission'),
        ),
    ]
