# Generated by Django 5.1.1 on 2024-11-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0027_remove_role_allowed_permit_role_allowed_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='allowed_permit',
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_section.permission'),
        ),
    ]
