# Generated by Django 5.1.1 on 2024-11-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0028_remove_role_allowed_permit_role_allowed_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.role')),
            ],
        ),
    ]
