# Generated by Django 5.1.1 on 2024-11-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0029_role_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role_permission',
            old_name='permission',
            new_name='permissions',
        ),
        migrations.RenameField(
            model_name='role_permission',
            old_name='role',
            new_name='roles',
        ),
    ]
