# Generated by Django 5.1.1 on 2024-11-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0030_rename_permission_role_permission_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='allowed_permit',
        ),
    ]
