# Generated by Django 5.1.1 on 2024-11-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0032_role_allowed_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='allowed_permit',
        ),
    ]
