# Generated by Django 5.1.1 on 2024-11-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0033_remove_role_allowed_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_users',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.role'),
        ),
    ]
