# Generated by Django 5.1.1 on 2024-11-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0034_alter_super_users_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='page_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
