# Generated by Django 5.1.1 on 2024-11-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0035_permission_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='admin_section.role_permission', to='admin_section.permission'),
        ),
    ]
