# Generated by Django 5.1.1 on 2024-11-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0036_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
    ]
