# Generated by Django 5.1.1 on 2024-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0037_remove_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='ulr_icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
