# Generated by Django 5.1.1 on 2024-11-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0038_permission_ulr_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='ulr_icon',
            new_name='url_icon',
        ),
    ]
