# Generated by Django 5.1.1 on 2024-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0039_rename_ulr_icon_permission_url_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
