# Generated by Django 5.1.1 on 2024-11-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0040_questions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.category')),
            ],
        ),
    ]
