# Generated by Django 5.1.1 on 2024-12-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0041_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizedits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateField()),
                ('updatedby', models.IntegerField()),
                ('q_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.questions')),
            ],
        ),
    ]
