# Generated by Django 5.1.1 on 2024-12-04 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0042_quizedits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizedits',
            name='addedon',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
