# Generated by Django 5.1.1 on 2024-12-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0043_alter_quizedits_addedon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizedits',
            old_name='addedon',
            new_name='added_on',
        ),
    ]
