# Generated by Django 5.1.1 on 2024-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0044_rename_addedon_quizedits_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='added_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
