# Generated by Django 5.1.1 on 2024-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0045_questions_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizedits',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
