# Generated by Django 5.1.1 on 2024-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0046_alter_quizedits_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='added_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
