# Generated by Django 5.1.1 on 2024-12-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0047_questions_added_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='status',
            new_name='verify_status',
        ),
    ]
