# Generated by Django 5.1.1 on 2024-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0048_rename_status_questions_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='verified_on',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
