# Generated by Django 5.1.1 on 2024-12-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0049_questions_verified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='verified_on',
            field=models.DateField(),
        ),
    ]
