# Generated by Django 5.1.1 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0050_alter_questions_verified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='verified_on',
            field=models.CharField(max_length=100),
        ),
    ]
