# Generated by Django 5.1.1 on 2024-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0051_alter_questions_verified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subcategory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
