# Generated by Django 5.1.1 on 2024-12-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0052_questions_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.subcategory'),
        ),
    ]
