# Generated by Django 5.1.1 on 2024-12-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0053_alter_questions_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_examid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('created_for', models.CharField(max_length=200)),
                ('no_questions', models.IntegerField()),
                ('subcat', models.CharField(max_length=200)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.category')),
            ],
        ),
    ]
