# Generated by Django 5.1.1 on 2024-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0054_create_examid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_examid',
            name='subcat',
        ),
        migrations.AddField(
            model_name='create_examid',
            name='subca',
            field=models.ManyToManyField(to='admin_section.subcategory'),
        ),
    ]
