# Generated by Django 5.1.1 on 2024-12-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0055_remove_create_examid_subcat_create_examid_subca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_examid',
            old_name='subca',
            new_name='subcat',
        ),
    ]
