# Generated by Django 5.1.1 on 2024-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0056_rename_subca_create_examid_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_examid',
            name='subcat',
        ),
        migrations.AddField(
            model_name='create_examid',
            name='subcat',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
