# Generated by Django 5.1.1 on 2024-12-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0057_remove_create_examid_subcat_create_examid_subcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_examid',
            old_name='cat_id',
            new_name='catid',
        ),
    ]
