# Generated by Django 5.1.1 on 2024-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0058_rename_cat_id_create_examid_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_examid',
            name='allowed_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
