# Generated by Django 5.1.1 on 2024-12-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0059_create_examid_allowed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.questions')),
            ],
        ),
    ]
