# Generated by Django 5.1.1 on 2024-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0060_exam_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('applied_time', models.DateTimeField()),
            ],
        ),
    ]
