# Generated by Django 5.1.1 on 2024-12-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0061_exam_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.IntegerField()),
                ('applicationid', models.IntegerField()),
                ('set_date', models.DateField()),
                ('set_time', models.TimeField()),
            ],
        ),
    ]
