# Generated by Django 5.1.1 on 2024-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0062_assign_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_exam',
            name='assigned_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign_exam',
            name='assigned_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
