# Generated by Django 5.1.1 on 2024-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0063_assign_exam_assigned_by_assign_exam_assigned_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_apply',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
