# Generated by Django 5.1.1 on 2025-01-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0064_exam_apply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('exam_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('application_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='assigned_attemptresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ans', models.CharField(max_length=50)),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admin_section.assigned_attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.questions')),
            ],
        ),
    ]
