# Generated by Django 5.1.1 on 2025-01-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0065_assigned_attempt_assigned_attemptresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_attempt',
            old_name='exam_id',
            new_name='examid',
        ),
        migrations.AddField(
            model_name='assigned_attempt',
            name='submited_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
