# Generated by Django 5.1.1 on 2025-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0066_rename_exam_id_assigned_attempt_examid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_attempt',
            name='exam_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
