# Generated by Django 5.1.1 on 2025-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0067_assigned_attempt_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_attempt',
            old_name='submited_on',
            new_name='submitted_on',
        ),
    ]
