# Generated by Django 5.1.1 on 2025-01-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0068_rename_submited_on_assigned_attempt_submitted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_attemptresult',
            old_name='attempt_id',
            new_name='attempt',
        ),
    ]
