# Generated by Django 5.1.1 on 2025-01-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0069_rename_attempt_id_assigned_attemptresult_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_examid',
            name='percentage_to_pass',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
