# Generated by Django 5.1.1 on 2025-02-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0070_create_examid_percentage_to_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('added_on', models.DateTimeField()),
                ('added_by', models.IntegerField()),
            ],
        ),
    ]
