# Generated by Django 5.1.1 on 2025-02-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0071_exam_planner'),
    ]

    operations = [
        migrations.CreateModel(
            name='planner_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.exam_apply')),
                ('planid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.exam_planner')),
            ],
        ),
    ]
