# Generated by Django 5.1.1 on 2025-02-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0072_planner_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner_list',
            name='added_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
