# Generated by Django 5.1.1 on 2025-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0073_planner_list_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner_list',
            name='examid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
