# Generated by Django 5.1.1 on 2025-02-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0074_planner_list_examid'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('applicationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.exam_apply')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.questions')),
            ],
        ),
    ]
